# Generated by Django 5.2 on 2025-05-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("berita", "0003_artikel_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="artikel",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
